# Generated by Django 5.2.5 on 2025-12-16 03:44

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Architecture',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('risque_tolere', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Coût maximal du risque toléré (en $)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'verbose_name': 'Architecture',
                'verbose_name_plural': 'Architectures',
                'db_table': 'architecture',
            },
        ),
        migrations.CreateModel(
            name='CategorieActif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(help_text='Code court pour la catégorie (ex: INFRA, APP, DATA)', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': "Catégorie d'actif",
                'verbose_name_plural': "Catégories d'actifs",
                'db_table': 'categorie_actif',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technique_code', models.CharField(help_text='Code unique de la technique (ex: T-001, T-002)', max_length=20, unique=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_technique', models.CharField(choices=[('TECHNIQUE', 'Technique'), ('ADMINISTRATIF', 'Administratif'), ('PHYSIQUE', 'Physique'), ('PREVENTIF', 'Préventif'), ('DETECTIF', 'Détectif'), ('CORRECTIF', 'Correctif')], max_length=50)),
                ('complexite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé')], default='MOYEN', max_length=10)),
                ('famille', models.CharField(blank=True, help_text='Famille de la technique (ex: Access Control, System Integrity, etc.)', max_length=100, null=True)),
                ('priorite', models.CharField(blank=True, choices=[('P0', 'P0 - Critique'), ('P1', 'P1 - Haute'), ('P2', 'P2 - Moyenne'), ('P3', 'P3 - Basse')], default='P2', max_length=10, null=True)),
            ],
            options={
                'verbose_name': 'Technique',
                'verbose_name_plural': 'Techniques',
                'db_table': 'technique',
            },
        ),
        migrations.CreateModel(
            name='Actif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('criticite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], default='MOYEN', max_length=10)),
                ('proprietaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('architecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actifs', to='api.architecture')),
            ],
            options={
                'verbose_name': 'Actif',
                'verbose_name_plural': 'Actifs',
                'db_table': 'actif',
            },
        ),
        migrations.CreateModel(
            name='AttributSecurite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_attribut', models.CharField(choices=[('CONFIDENTIALITE', 'Confidentialité'), ('INTEGRITE', 'Intégrité'), ('DISPONIBILITE', 'Disponibilité'), ('AUTHENTIFICATION', 'Authentification'), ('AUTORISATION', 'Autorisation'), ('NON_REPUDIATION', 'Non-répudiation')], max_length=20)),
                ('cout_compromission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coût financier en cas de compromission de cet attribut (en $)', max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('priorite', models.CharField(choices=[('P0', 'P0 - Critique'), ('P1', 'P1 - Haute'), ('P2', 'P2 - Moyenne'), ('P3', 'P3 - Basse')], default='P2', max_length=10)),
                ('actif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributs_securite', to='api.actif')),
            ],
            options={
                'verbose_name': 'Attribut de sécurité',
                'verbose_name_plural': 'Attributs de sécurité',
                'db_table': 'attribut_securite',
                'unique_together': {('actif', 'type_attribut')},
            },
        ),
        migrations.CreateModel(
            name='LogActivite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=100)),
                ('objet_type', models.CharField(max_length=100)),
                ('objet_id', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Log d'activité",
                'verbose_name_plural': "Logs d'activité",
                'db_table': 'log_activite',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Menace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('type_menace', models.CharField(choices=[('Spoofing', "S - Usurpation d'identité"), ('Tampering', 'T - Altération des données'), ('Repudiation', 'R - Répudiation'), ('Information Disclosure', "I - Divulgation d'informations"), ('Denial of Service (DoS)', 'D - Déni de service'), ('Elevation of Privilege', 'E - Élévation de privilèges'), ('AUTRE', 'Autre')], default='Spoofing', max_length=50)),
                ('severite', models.CharField(choices=[('FAIBLE', 'Faible'), ('MOYEN', 'Moyen'), ('ELEVE', 'Élevé'), ('CRITIQUE', 'Critique')], max_length=10)),
                ('attribut_securite_principal', models.ForeignKey(blank=True, help_text='Attribut de sécurité principal pour cette menace', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menaces_principales', to='api.attributsecurite')),
            ],
            options={
                'verbose_name': 'Menace',
                'verbose_name_plural': 'Menaces',
                'db_table': 'menace',
            },
        ),
        migrations.CreateModel(
            name='AttributMenace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('probabilite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Probabilité d'occurrence (0-100%)", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Impact sur l'attribut de sécurité (0-100%)", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cout_impact', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Coût financier estimé de l'impact", max_digits=15)),
                ('attribut_securite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menaces', to='api.attributsecurite')),
                ('menace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributs_impactes', to='api.menace')),
            ],
            options={
                'verbose_name': 'Attribut-Menace',
                'verbose_name_plural': 'Attributs-Menaces',
                'db_table': 'attribut_menace',
                'unique_together': {('attribut_securite', 'menace')},
            },
        ),
        migrations.CreateModel(
            name='MesureDeControle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mesure_code', models.CharField(help_text='Code unique de la mesure (ex: M-001, M-002)', max_length=30, unique=True)),
                ('nature_mesure', models.CharField(choices=[('IS', 'IS - Implémentation Système'), ('IP', 'IP - Implémentation Processus'), ('RC', 'RC - Révision Configuration'), ('RA', 'RA - Révision Architecture')], default='IS', max_length=50)),
                ('cout_mise_en_oeuvre', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Coût initial d'implémentation", max_digits=15)),
                ('cout_maintenance_annuel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Coût de maintenance annuel', max_digits=15)),
                ('efficacite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Efficacité de la mesure (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('duree_implementation', models.IntegerField(default=30, help_text="Durée d'implémentation en jours")),
                ('ressources_necessaires', models.TextField(blank=True, help_text='Description des ressources humaines/techniques nécessaires', null=True)),
                ('technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_controle', to='api.technique')),
            ],
            options={
                'verbose_name': 'Mesure de contrôle',
                'verbose_name_plural': 'Mesures de contrôle',
                'db_table': 'mesure_de_controle',
            },
        ),
        migrations.CreateModel(
            name='TypeActif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(help_text='Code court pour le type (ex: SRV-WEB, SRV-DB, APP-WEB)', max_length=20, unique=True)),
                ('categorie', models.ForeignKey(help_text="Catégorie parente de ce type d'actif", on_delete=django.db.models.deletion.PROTECT, related_name='types_actifs', to='api.categorieactif')),
            ],
            options={
                'verbose_name': "Type d'actif",
                'verbose_name_plural': "Types d'actifs",
                'db_table': 'type_actif',
                'ordering': ['categorie', 'nom'],
                'unique_together': {('categorie', 'nom')},
            },
        ),
        migrations.AddField(
            model_name='actif',
            name='type_actif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actifs', to='api.typeactif'),
        ),
        migrations.CreateModel(
            name='MenaceMesure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('efficacite', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Efficacité de cette mesure contre cette menace (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('statut_conformite', models.CharField(choices=[('NON_CONFORME', 'Non conforme'), ('PARTIELLEMENT', 'Partiellement conforme'), ('CONFORME', 'Conforme'), ('NON_APPLICABLE', 'Non applicable')], default='NON_CONFORME', max_length=20)),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('menace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesures_controle', to='api.menace')),
                ('mesure_controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menaces_traitees', to='api.mesuredecontrole')),
            ],
            options={
                'verbose_name': 'Menace-Mesure',
                'verbose_name_plural': 'Menaces-Mesures',
                'db_table': 'menace_mesure',
                'unique_together': {('menace', 'mesure_controle')},
            },
        ),
        migrations.CreateModel(
            name='ImplementationMesure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_COURS', 'En cours'), ('IMPLEMENTE', 'Implémenté'), ('VERIFIE', 'Vérifié'), ('ANNULE', 'Annulé')], default='PLANIFIE', max_length=20)),
                ('date_debut_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_fin_prevue', models.DateTimeField(blank=True, null=True)),
                ('date_implementation', models.DateTimeField(blank=True, null=True)),
                ('equipe', models.TextField(blank=True, help_text="Membres de l'équipe impliqués", null=True)),
                ('pourcentage_avancement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('commentaires', models.TextField(blank=True, null=True)),
                ('obstacles', models.TextField(blank=True, help_text='Obstacles rencontrés', null=True)),
                ('attribut_menace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='api.attributmenace')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('mesure_controle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implementations', to='api.mesuredecontrole')),
            ],
            options={
                'verbose_name': 'Implémentation de mesure',
                'verbose_name_plural': 'Implémentations de mesures',
                'db_table': 'implementation_mesure',
                'unique_together': {('attribut_menace', 'mesure_controle')},
            },
        ),
    ]
