# Generated by Django 5.2.5 on 2025-09-03 21:51

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_update_architecture_risk_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributmenace',
            name='impact',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Impact sur l'attribut de sécurité (0-100%)", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='attributmenace',
            name='probabilite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Probabilité d'occurrence (0-100%)", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='attributsecurite',
            name='valeur_cible',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Niveau de sécurité requis (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='controlenist',
            name='priorite',
            field=models.CharField(choices=[('P0', 'P0 - Critique'), ('P1', 'P1 - Haute'), ('P2', 'P2 - Moyenne'), ('P3', 'P3 - Basse')], default='P2', max_length=10),
        ),
        migrations.AlterField(
            model_name='menacecontrole',
            name='efficacite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Efficacité du contrôle contre cette menace (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mesuredecontrole',
            name='efficacite',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Efficacité de la mesure (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
