# Generated by Django 5.2.5 on 2025-09-09 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_simplify_attribut_securite_to_single_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='technique_code',
            field=models.CharField(blank=True, help_text='Code unique de la technique (ex: AC-2.1, SI-4.a)', max_length=20, null=True, unique=True),
        ),
    ]
