# Generated by Django 5.2.5 on 2025-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_menace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menace',
            name='type_menace',
            field=models.CharField(choices=[('Spoofing', "Spoofing - Usurpation d'identité"), ('Tampering', 'Tampering - Altération des données'), ('Repudiation', 'Repudiation - Répudiation'), ('Information Disclosure', "Information Disclosure - Divulgation d'informations"), ('Denial of Service (DoS)', 'Denial of Service (DoS) - Déni de service'), ('Elevation of Privilege', 'Elevation of Privilege - Élévation de privilèges'), ('AUTRE', 'Autre')], default='Spoofing', max_length=50),
        ),
    ]
