# Generated by Django 5.2.5 on 2025-09-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_menace_type_menace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menace',
            name='type_menace',
            field=models.CharField(choices=[('Spoofing', "S - Usurpation d'identité"), ('Tampering', 'T - Altération des données'), ('Repudiation', 'R - Répudiation'), ('Information Disclosure', "I - Divulgation d'informations"), ('Denial of Service (DoS)', 'D - Déni de service'), ('Elevation of Privilege', 'E - Élévation de privilèges'), ('AUTRE', 'Autre')], default='Spoofing', max_length=50),
        ),
    ]
