# Generated by Django 5.2.5 on 2025-09-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_menace_type_menace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlenist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
