# Generated by Django 5.2.5 on 2025-09-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_controlenist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlenist',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée du contrôle NIST', null=True),
        ),
        migrations.AlterField(
            model_name='controlenist',
            name='priorite',
            field=models.CharField(blank=True, choices=[('P0', 'P0 - Critique'), ('P1', 'P1 - Haute'), ('P2', 'P2 - Moyenne'), ('P3', 'P3 - Basse')], default='P2', max_length=10, null=True),
        ),
    ]
