# Generated by Django 5.2.5 on 2025-09-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_controlenist_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesuredecontrole',
            name='mesure_code',
            field=models.CharField(blank=True, help_text='Code unique de la mesure (ex: AC-2.1.01, SI-4.a.01)', max_length=30, null=True),
        ),
    ]
