# Generated by Django 5.2.5 on 2025-09-30 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_mesuredecontrole_mesure_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesuredecontrole',
            name='nature_mesure',
            field=models.CharField(choices=[('IS', 'IS - Implémentation Système'), ('IP', 'IP - Implémentation Processus'), ('RC', 'RC - Révision Configuration'), ('RA', 'RA - Révision Architecture')], default='IS', max_length=50),
        ),
    ]
