# Generated by Django 5.2.5 on 2025-12-03 21:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_mesuredecontrole_nature_mesure'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieActif',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('code', models.CharField(help_text='Code court pour la catégorie (ex: INFRA, APP, DATA)', max_length=20, unique=True)),
            ],
            options={
                'verbose_name': "Catégorie d'actif",
                'verbose_name_plural': "Catégories d'actifs",
                'db_table': 'categorie_actif',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterModelOptions(
            name='typeactif',
            options={'ordering': ['nom'], 'verbose_name': "Type d'actif", 'verbose_name_plural': "Types d'actifs"},
        ),
        migrations.AddField(
            model_name='typeactif',
            name='code',
            field=models.CharField(blank=True, help_text='Code court pour le type (ex: SRV-WEB, SRV-DB, APP-WEB)', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='typeactif',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='typeactif',
            name='categorie',
            field=models.ForeignKey(blank=True, help_text="Catégorie parente de ce type d'actif", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='types_actifs', to='api.categorieactif'),
        ),
    ]
