# Generated by Django 5.2.5 on 2025-12-03 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_categorieactif_alter_typeactif_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeactif',
            options={'ordering': ['categorie', 'nom'], 'verbose_name': "Type d'actif", 'verbose_name_plural': "Types d'actifs"},
        ),
        migrations.AlterField(
            model_name='typeactif',
            name='categorie',
            field=models.ForeignKey(help_text="Catégorie parente de ce type d'actif", on_delete=django.db.models.deletion.PROTECT, related_name='types_actifs', to='api.categorieactif'),
        ),
        migrations.AlterField(
            model_name='typeactif',
            name='code',
            field=models.CharField(help_text='Code court pour le type (ex: SRV-WEB, SRV-DB, APP-WEB)', max_length=20, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='typeactif',
            unique_together={('categorie', 'nom')},
        ),
    ]
